# 프론트엔드 자동 배포 환경 
name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend repo
      uses: actions/checkout@v3

    - name: SSH into Azure VM and deploy frontend
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          cd ~/KNU_Capstone_Frontend
          git pull origin main
          npm install
          npm run build
          cd ~
          docker-compose up -d nginx